// Builds dist/*.cjs from src/*.js so require("tripwire-guardrails") works on every Node 20+ (no dependencies).
// The transform only handles the import/export forms this repo uses and fails loudly on anything else.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
mkdirSync("dist", { recursive: true });
const files = ["rules", "normalize", "judge", "stream", "express", "index"];
for (const name of files) {
  let s = readFileSync(`src/${name}.js`, "utf8");
  const names = [];
  s = s.replace(/^import \{([^}]+)\} from "\.\/(\w+)\.js";$/gm, (_, list, mod) => `const {${list}} = require("./${mod}.cjs");`);
  s = s.replace(/^export (async function|function|const) (\w+)/gm, (_, kind, n) => { names.push(n); return `${kind} ${n}`; });
  s = s.replace(/^export \{([^}]+)\};$/gm, (_, list) => { list.split(",").map((x) => x.trim()).filter(Boolean).forEach((n) => { if (!names.includes(n)) names.push(n); }); return ""; });
  if (/^(import|export) /m.test(s)) throw new Error(`${name}.js uses an import/export form the CJS build does not handle`);
  writeFileSync(`dist/${name}.cjs`, `"use strict";\n// Generated by scripts/build-cjs.mjs from src/${name}.js. Do not edit.\n${s}\nmodule.exports = { ${names.join(", ")} };\n`);
}
console.log("built", files.map((f) => `dist/${f}.cjs`).join(", "));
